---
- name: Set up a Fedora development environment
  hosts: fedora
  become: yes
  tasks:
    - name: Update Fedora
      raw: /usr/bin/dnf -y update 

    - name: Upgrade Fedora
      raw: /usr/bin/dnf -y update
    
    - name: Install development tools
      dnf:
        name:
          - git
          - neovim
          - neofetch
          - python3-pip
          - python3-devel
          - docker
        state: present

    - name: Start and enable Docker 
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add fedora user to Docker group
      user:
        name: fedora
        groups: docker
        append: yes
